

name: build_cyb

on:
  push:
    branches: 
      - master

jobs:
  build_cyb:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Build & Publish
      run: |
        yarn build
        echo "Built!"
        cd $commit_files
        echo "In build repo"
        git init
        echo "Initiated"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        echo "cyb.ai" > CNAME
        git add --all
        git commit -m "build cyb"
        echo "Commited"
        git push -q -f https://$github_token@github.com/cybercongress/dot-cyber.git master:build
        echo "Pushed"
      env:
        NODE_OPTIONS: "--max-old-space-size=8192"
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        commit_files: build
        branch: build
        CHAIN_ID: "bostrom"
        
