

name: build_cyb

on:
  push:
    branches: 
      - master

jobs:
  build_cyb:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: |
        yarn build
        export CHAIN_ID="bostrom" 
      env:
        NODE_OPTIONS: "--max-old-space-size=8192"
        
    - name: Publish
      run: |
        git clone --depth 1 https://x-access-token:$github_token@github.com/$repository.git /$repository
        rm -rf /$repository/*
        cp -r ./$commit_files /$repository
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        echo "cyb.ai" > ./$commit_files/CNAME
        git add --all
        git commit -m "build cyb"
        git push origin $branch
        rm -rf /$repository
      env:
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        commit_files: build
        branch: build
